### ISSUE TITLE
User creation isn't always upserting correctly

### ISSUE THREAD

**Issue by zacstewart** [zacstewart/tech404logs#15]
When a new user joins the team, it seems like I try to create it twice, causing a SQL exception.

I think it's because I get a `team_join` event and a `channel_join` (for #general) nearly simultaneously, and they both get handled at the same time asynchronously.
```
 A, [2015-12-02T02:49:12.674688 #6] ANY -- : 2015-12-02 02:49:12 +0000 severity=DEBUG, RTM message received: {"type":"presence_change","user":"U0CFPFSTW","presence":"away"}
» 1 Dec 2015 21:49:13.076 2015-12-02 02:49:12.706708+00:00 app web.1 - - A, [2015-12-02T02:49:12.706635 #6] ANY -- : 2015-12-02 02:49:12 +0000 severity=DEBUG, RTM message received: {"type":"presence_change","user":"U03HA8NTF","presence":"away"}
» 1 Dec 2015 21:49:13.132 2015-12-02 02:49:12.770786+00:00 app web.1 - - A, [2015-12-02T02:49:12.770714 #6] ANY -- : 2015-12-02 02:49:12 +0000 severity=DEBUG, RTM message received: {"type":"presence_change","user":"U04B1MYEV","presence":"away"}
» 1 Dec 2015 21:49:13.997 2015-12-02 02:49:13.701632+00:00 app web.1 - - A, [2015-12-02T02:49:13.701525 #6] ANY -- : 2015-12-02 02:49:13 +0000 severity=DEBUG, RTM message received: {"type":"team_join","user":{"id":"U0FM52NPP","team_id":"T03GVRCFS","name":"smagic39","deleted":false,"status":null,"color":"8f4a2b","real_name":"","tz":"Asia/Novosibirsk","tz_label":"Novosibirsk Time","tz_offset":21600,"profile":{"avatar_hash":"g83b9dd9c17c","real_name":"","real_name_normalized":"","email":"smagic39@gmail.com","image_24":"https://secure.gravatar.com/avatar/83b9dd9c17cdced7f9e805e06d93dc76.jpg?s=24&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F66f9%2Fimg%2Favatars%2Fava_0004-24.png","image_32":"https://secure.gravatar.com/avatar/83b9dd9c17cdced7f9e805e06d93dc76.jpg?s=32&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F66f9%2Fimg%2Favatars%2Fava_0004-32.png","image_48":"https://secure.gravatar.com/avatar/83b9dd9c17cdced7f9e805e06d93dc76.jpg?s=48&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F66f9%2Fimg%2Favatars%2Fava_0004-48.png","image_72":"https://secure.gravatar.com/avatar/83b9dd9c17cdced7f9e805e06d93dc76.jpg?s=72&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F66f9%2Fimg%2Favatars%2Fava_0004-72.png","image_192":"https://secure.gravatar.com/avatar/83b9dd9c17cdced7f9e805e06d93dc76.jpg?s=192&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F7fa9%2Fimg%2Favatars%2Fava_0004-192.png","image_512":"https://secure.gravatar.com/avatar/83b9dd9c17cdced7f9e805e06d93dc76.jpg?s=512&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F7fa9%2Fimg%2Favatars%2Fava_0004-512.png","fields":null},"is_admin":false,"is_owner":false,"is_primary_owner":false,"is_restricted":false,"is_ultra_restricted":false,"is_bot":false,"presence":"away"},"cache_ts":1449024553}
» 1 Dec 2015 21:49:17.539 2015-12-02 02:49:17.255470+00:00 app web.1 - - A, [2015-12-02T02:49:17.255381 #6] ANY -- : 2015-12-02 02:49:17 +0000 severity=DEBUG, RTM message received: {"user":"U0FM52NPP","type":"message","subtype":"channel_join","text":"<@U0FM52NPP|smagic39> has joined the channel","channel":"C03GVRCGE","ts":"1449024553.001721"}
» 1 Dec 2015 21:49:17.625 2015-12-02 02:49:17.256889+00:00 app web.1 - - ~ (0.000706) SET standard_conforming_strings = on
» 1 Dec 2015 21:49:17.625 2015-12-02 02:49:17.258263+00:00 app web.1 - - ~ (0.000683) SET datestyle = ISO
» 1 Dec 2015 21:49:17.625 2015-12-02 02:49:17.276230+00:00 app web.1 - - ~ (0.000691) SET backslash_quote = off
» 1 Dec 2015 21:49:17.625 2015-12-02 02:49:17.277550+00:00 app web.1 - - ~ (0.000589) SET client_min_messages = warning
» 1 Dec 2015 21:49:17.625 2015-12-02 02:49:17.278948+00:00 app web.1 - - ~ default: begin
» 1 Dec 2015 21:49:17.625 2015-12-02 02:49:17.282707+00:00 app web.1 - - ~ (0.001933) SELECT "id", "name", "real_name", "image" FROM "tech404_index_users" WHERE "id" = 'U0FM52NPP' ORDER BY "id" LIMIT 1
» 1 Dec 2015 21:49:17.648 2015-12-02 02:49:17.256144+00:00 app web.1 - - ~ (0.000988) SET backslash_quote = off
» 1 Dec 2015 21:49:17.745 2015-12-02 02:49:17.257538+00:00 app web.1 - - ~ (0.000611) SET client_min_messages = warning
» 1 Dec 2015 21:49:17.745 2015-12-02 02:49:17.275698+00:00 app web.1 - - ~ (0.016561) SELECT "id", "name", "real_name", "image" FROM "tech404_index_users" WHERE "id" = 'U0FM52NPP' ORDER BY "id" LIMIT 1
» 1 Dec 2015 21:49:17.745 2015-12-02 02:49:17.276921+00:00 app web.1 - - ~ (0.000645) SET standard_conforming_strings = on
» 1 Dec 2015 21:49:17.745 2015-12-02 02:49:17.278201+00:00 app web.1 - - ~ (0.000620) SET datestyle = ISO
» 1 Dec 2015 21:49:17.745 2015-12-02 02:49:17.280303+00:00 app web.1 - - ~ (0.000592) BEGIN
» 1 Dec 2015 21:49:17.894 2015-12-02 02:49:17.611667+00:00 app web.1 - - ~ (0.331980) INSERT INTO "tech404_index_users" ("id", "name", "real_name", "image") VALUES ('U0FM52NPP', 'smagic39', '', 'https://secure.gravatar.com/avatar/83b9dd9c17cdced7f9e805e06d93dc76.jpg?s=48&d=https%3A%2F%2Fslack.global.ssl.fastly.net%2F66f9%2Fimg%2Favatars%2Fava_0004-48.png')
» 1 Dec 2015 21:49:17.896 2015-12-02 02:49:17.619865+00:00 app web.1 - - ~ ERROR: duplicate key value violates unique constraint "tech404_index_users_pkey"
» 1 Dec 2015 21:49:17.896 2015-12-02 02:49:17.619867+00:00 app web.1 - - DETAIL: Key (id)=(U0FM52NPP) already exists.
» 1 Dec 2015 21:49:17.896 2015-12-02 02:49:17.619868+00:00 app web.1 - - (code: 83906754, sql state: 23505, query: INSERT INTO "tech404_index_users" ("id") VALUES ('U0FM52NPP'), uri: postgres:vmqaqlormfetno@ec2-54-197-238-19.compute-1.amazonaws.com:5432/d8gpnnp2d6fpd4?scheme=postgres&user=vmqaqlormfetno&password=eRISDClarSJZooz1YNw9_9DTyr&host=ec2-54-197-238-19.compute-1.amazonaws.com&port=5432&path=/d8gpnnp2d6fpd4&query=&fragment=&adapter=postgres)
» 1 Dec 2015 21:49:17.896 2015-12-02 02:49:17.621052+00:00 app web.1 - - ~ default: rollback
» 1 Dec 2015 21:49:17.896 2015-12-02 02:49:17.622488+00:00 app web.1 - - A, [2015-12-02T02:49:17.622433 #6] ANY -- : 2015-12-02 02:49:17 +0000 severity=DEBUG, RTM connection closed: 1006,
» 1 Dec 2015 21:49:17.896 2015-12-02 02:49:17.612119+00:00 app web.1 - - ~ (0.328882) INSERT INTO "tech404_index_users" ("id") VALUES ('U0FM52NPP')
» 1 Dec 2015 21:49:17.896 2015-12-02 02:49:17.621790+00:00 app web.1 - - ~ (0.000640) ROLLBACK
» 1 Dec 2015 21:49:17.897 2015-12-02 02:49:17.826159+00:00 app web.1 - - /app/vendor/bundle/ruby/2.0.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:114:in `execute_non_query': ERROR: duplicate key value violates unique constraint "tech404_index_users_pkey" (DataObjects::IntegrityError) Exception
» 1 Dec 2015 21:49:17.897 2015-12-02 02:49:17.826162+00:00 app web.1 - - DETAIL: Key (id)=(U0FM52NPP) already exists.
» 1 Dec 2015 21:49:17.897 2015-12-02 02:49:17.826163+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:114:in `block (2 levels) in create'
» 1 Dec 2015 21:49:17.897 2015-12-02 02:49:17.826164+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
» 1 Dec 2015 21:49:17.897 2015-12-02 02:49:17.826164+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:113:in `block in create'
» 1 Dec 2015 21:49:17.897 2015-12-02 02:49:17.826165+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:85:in `each'
```

**Comment by zacstewart** [comment]
Tentatively fixed by commit 0da5a24cfc0d408edb576f0e91583722ee19c956
