### ISSUE TITLE
User.store and Message.store aren't atomic

### ISSUE THREAD

**Issue by zacstewart** [zacstewart/tech404logs#17]
`first_or_create` apparently doesn't find a first record, and tries to create it, but in the meantime, one has already been created.

```
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.434652+00:00 app web.1 - - ~ (0.013541) ROLLBACK
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.438345+00:00 app web.1 - - A, [2016-03-21T16:04:49.438269 #6] ANY -- : 2016-03-21 16:04:49 +0000 severity=DEBUG, RTM connection closed: 1006,
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660504+00:00 app web.1 - - /app/vendor/bundle/ruby/2.0.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:114:in `execute_non_query': ERROR: duplicate key value violates unique constraint "tech404_index_users_pkey" (DataObjects::IntegrityError) Exception
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660513+00:00 app web.1 - - DETAIL: Key (id)=(U0U886F2Q) already exists.
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660517+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:114:in `block (2 levels) in create'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660518+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660518+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:113:in `block in create'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660520+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:85:in `each'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660521+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:85:in `create'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660522+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/repository.rb:146:in `create'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660541+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/resource/persistence_state/transient.rb:74:in `create_resource'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660542+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/resource/persistence_state/transient.rb:25:in `commit'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660543+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:963:in `_persist'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660543+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:977:in `block in create_with_hooks'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660544+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:974:in `catch'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660559+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:974:in `create_with_hooks'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660560+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:1028:in `save_self'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660560+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-validations-1.2.0/lib/dm-validations.rb:54:in `save_self'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660561+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:1013:in `block in _save'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660562+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:1229:in `run_once'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660562+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:1012:in `_save'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660563+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb:412:in `save'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660563+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-validations-1.2.0/lib/dm-validations.rb:40:in `block in save'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660565+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-validations-1.2.0/lib/dm-validations/context.rb:16:in `in_context'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660565+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-validations-1.2.0/lib/dm-validations.rb:40:in `save'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660566+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-validations-1.2.0/lib/dm-validations.rb:130:in `create'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660567+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-core-1.2.1/lib/dm-core/model.rb:445:in `first_or_create'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660585+00:00 app web.1 - - from /app/lib/tech404logs/user.rb:24:in `store'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660587+00:00 app web.1 - - from /app/lib/tech404logs/message.rb:19:in `block in store'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660589+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-transactions-1.2.0/lib/dm-transactions.rb:373:in `block in transaction'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660589+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-transactions-1.2.0/lib/dm-transactions.rb:131:in `block in commit'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660591+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-transactions-1.2.0/lib/dm-transactions.rb:195:in `within'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660592+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-transactions-1.2.0/lib/dm-transactions.rb:131:in `commit'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660607+00:00 app web.1 - - from /app/vendor/bundle/ruby/2.0.0/gems/dm-transactions-1.2.0/lib/dm-transactions.rb:373:in `transaction'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660609+00:00 app web.1 - - from /app/lib/tech404logs/message.rb:16:in `store'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660611+00:00 app web.1 - - from /app/lib/tech404logs/message_handler.rb:21:in `handle'
» 21 Mar 2016 12:04:49.824 2016-03-21 16:04:49.660612+00:00 app web.1 - - from /app/lib/tech404logs/message_handler.rb:4:in `handle'
» 21 Mar 2016 12:04:49.899 2016-03-21 16:04:49.660614+00:00 app web.1 - - from /app/lib/tech404logs/event_handler.rb:17:in `handle'
» 21 Mar 2016 12:04:49.899 2016-03-21 16:04:49.660631+00:00 app web.1 - - from /app/lib/tech404logs/event_handler.rb:4:in `handle'
» 21 Mar 2016 12:04:49.899 2016-03-21 16:04:49.660708+00:00 app web.1 - - from /app/lib/tech404logs/connection.rb:32:in `block in on_message'
```

**Comment by zacstewart** [comment]
Doh. Duplicate of #15
